export const Students_Table = "Students_Table"
export const Hobby_Table = "Hobby_Table"
export const Hobby_Student = "Hobby_Student"
export const Classes_Table = "Classes_Table"
export const Teachers_Table = "Teachers_Table"
export const Specialities_Table = "Specialities_Table"
export const Specialities_Teachers = "Specialities_Teachers"
